// NOTE: This is a boilerplate file generated by the `generate-express` CLI
// The author has removed unused packages, and used `const` instead of `var`
// but hasn't changed this in any other way
const createError = require('http-errors')
const express = require('express')
const logger = require('morgan')

const router = require('./router')

const app = express()

app.use(logger('dev'))
app.use(express.json())
app.use(express.urlencoded({ extended: false }))

app.use('/', router)

// catch 404 and forward to error handler
app.use(function (req, res, next) { next(createError(404)) })

// error handler
app.use(function (err, req, res) {
  console.error(err)

  // set locals, only providing error in development
  res.locals.message = err.message
  res.locals.error = req.app.get('env') === 'development' ? err : {}

  // render the error page
  res.status(err.status || 500)
  res.json({ error: "Oops, an error ocurred" })
})

module.exports = app
